version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: waw-backend:latest
    ports:
      - "8000:8000"
    env_file:
      - .env.docker
    restart: unless-stopped
