version: "3.9"
services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: waw
      POSTGRES_USER: waw
      POSTGRES_PASSWORD: changeMeStrong
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "waw"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.production
    environment:
      DATABASE_URL: postgresql://waw:changeMeStrong@db:5432/waw
      LOGIN_RATE_LIMIT_WINDOW: 300
      LOGIN_RATE_LIMIT_MAX: 10
      LOGIN_BLOCK_SECONDS: 300
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    restart: unless-stopped

  dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    environment:
      NEXT_PUBLIC_API_BASE: http://localhost:8000
    depends_on:
      - api
    ports:
      - "3000:3000"
    restart: unless-stopped

volumes:
  db_data: