services:
  - type: web
    name: waw-backend
    env: python
    buildCommand: pip install -r requirements.backend.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: DATABASE_URL
        fromDatabase:
          name: waw-postgres
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGINS
        value: "https://your-frontend-domain.com,http://localhost:3000"
      - key: ADMIN_EMAILS
        value: "your-email@example.com"
      - key: ADMIN_SHARED_PASSWORD
        value: "your-secure-admin-password"

databases:
  - name: waw-postgres
    databaseName: waw_production
    user: waw_user
